config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'articles', to: 'articles#index'
  get "articles/new", to: "articles#new"
  post "articles", to: "articles#create"
  get 'articles/:id', to: 'articles#show', as: 'article'
  get "articles/:id/edit", to: "articles#edit", as: 'edit'
  patch "articles/:id", to: "articles#update"
  delete "articles/:id", to: "articles#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    set_article
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def edit
    set_article
  end

  def update
    set_article
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    set_article
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Wikinimous</h1>

<ul>
  <% @articles.each do |article| %>
    <li> <%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

<%= link_to 'Create a new article', articles_new_path %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1>
  Article: <%= @article.title %>
</h1>

<p> Content: <%= @article.content %> </p>

<%= link_to 'Go back', articles_path %>

<%= link_to 'Update this article', edit_path %>

<%= link_to "Delete",
  article_path(@article),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>